/* tslint:disable */
/* eslint-disable */
/**
 * Intent API
 * REST API for the Intent Ecosystem.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthLogoutRequest,
  AuthPasswordResetConfirmRequest,
  AuthPasswordResetRequest200Response,
  AuthPasswordResetRequestRequest,
  AuthRefreshRequest,
  AuthSessionResponse,
  ErrorResponse,
  LoginRequest,
  SignupRequest,
} from '../models/index';
import {
    AuthLogoutRequestFromJSON,
    AuthLogoutRequestToJSON,
    AuthPasswordResetConfirmRequestFromJSON,
    AuthPasswordResetConfirmRequestToJSON,
    AuthPasswordResetRequest200ResponseFromJSON,
    AuthPasswordResetRequest200ResponseToJSON,
    AuthPasswordResetRequestRequestFromJSON,
    AuthPasswordResetRequestRequestToJSON,
    AuthRefreshRequestFromJSON,
    AuthRefreshRequestToJSON,
    AuthSessionResponseFromJSON,
    AuthSessionResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    LoginRequestFromJSON,
    LoginRequestToJSON,
    SignupRequestFromJSON,
    SignupRequestToJSON,
} from '../models/index';

export interface AuthLoginRequest {
    loginRequest: LoginRequest;
}

export interface AuthLogoutOperationRequest {
    authLogoutRequest?: AuthLogoutRequest;
}

export interface AuthPasswordResetConfirmOperationRequest {
    authPasswordResetConfirmRequest: AuthPasswordResetConfirmRequest;
}

export interface AuthPasswordResetRequestOperationRequest {
    authPasswordResetRequestRequest: AuthPasswordResetRequestRequest;
}

export interface AuthRefreshOperationRequest {
    authRefreshRequest: AuthRefreshRequest;
}

export interface AuthSignupRequest {
    signupRequest: SignupRequest;
}

export interface DeletePATRequest {
    id: number;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Login with email and password
     */
    async authLoginRaw(requestParameters: AuthLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthSessionResponse>> {
        if (requestParameters['loginRequest'] == null) {
            throw new runtime.RequiredError(
                'loginRequest',
                'Required parameter "loginRequest" was null or undefined when calling authLogin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestToJSON(requestParameters['loginRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthSessionResponseFromJSON(jsonValue));
    }

    /**
     * Login with email and password
     */
    async authLogin(requestParameters: AuthLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthSessionResponse> {
        const response = await this.authLoginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Logout and revoke refresh sessions
     */
    async authLogoutRaw(requestParameters: AuthLogoutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/auth/logout`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthLogoutRequestToJSON(requestParameters['authLogoutRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Logout and revoke refresh sessions
     */
    async authLogout(requestParameters: AuthLogoutOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authLogoutRaw(requestParameters, initOverrides);
    }

    /**
     * Confirm password reset
     */
    async authPasswordResetConfirmRaw(requestParameters: AuthPasswordResetConfirmOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['authPasswordResetConfirmRequest'] == null) {
            throw new runtime.RequiredError(
                'authPasswordResetConfirmRequest',
                'Required parameter "authPasswordResetConfirmRequest" was null or undefined when calling authPasswordResetConfirm().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/auth/password/reset/confirm`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthPasswordResetConfirmRequestToJSON(requestParameters['authPasswordResetConfirmRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Confirm password reset
     */
    async authPasswordResetConfirm(requestParameters: AuthPasswordResetConfirmOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authPasswordResetConfirmRaw(requestParameters, initOverrides);
    }

    /**
     * Request password reset
     */
    async authPasswordResetRequestRaw(requestParameters: AuthPasswordResetRequestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthPasswordResetRequest200Response>> {
        if (requestParameters['authPasswordResetRequestRequest'] == null) {
            throw new runtime.RequiredError(
                'authPasswordResetRequestRequest',
                'Required parameter "authPasswordResetRequestRequest" was null or undefined when calling authPasswordResetRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/auth/password/reset/request`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthPasswordResetRequestRequestToJSON(requestParameters['authPasswordResetRequestRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthPasswordResetRequest200ResponseFromJSON(jsonValue));
    }

    /**
     * Request password reset
     */
    async authPasswordResetRequest(requestParameters: AuthPasswordResetRequestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthPasswordResetRequest200Response> {
        const response = await this.authPasswordResetRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Refresh access token
     */
    async authRefreshRaw(requestParameters: AuthRefreshOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthSessionResponse>> {
        if (requestParameters['authRefreshRequest'] == null) {
            throw new runtime.RequiredError(
                'authRefreshRequest',
                'Required parameter "authRefreshRequest" was null or undefined when calling authRefresh().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/auth/refresh`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthRefreshRequestToJSON(requestParameters['authRefreshRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthSessionResponseFromJSON(jsonValue));
    }

    /**
     * Refresh access token
     */
    async authRefresh(requestParameters: AuthRefreshOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthSessionResponse> {
        const response = await this.authRefreshRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create account and start session
     */
    async authSignupRaw(requestParameters: AuthSignupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthSessionResponse>> {
        if (requestParameters['signupRequest'] == null) {
            throw new runtime.RequiredError(
                'signupRequest',
                'Required parameter "signupRequest" was null or undefined when calling authSignup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/auth/signup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignupRequestToJSON(requestParameters['signupRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthSessionResponseFromJSON(jsonValue));
    }

    /**
     * Create account and start session
     */
    async authSignup(requestParameters: AuthSignupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthSessionResponse> {
        const response = await this.authSignupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create PAT
     */
    async createPATRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/auth/tokens`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create PAT
     */
    async createPAT(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createPATRaw(initOverrides);
    }

    /**
     * Delete PAT
     */
    async deletePATRaw(requestParameters: DeletePATRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePAT().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/auth/tokens/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete PAT
     */
    async deletePAT(requestParameters: DeletePATRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePATRaw(requestParameters, initOverrides);
    }

    /**
     * List personal access tokens (PAT)
     */
    async listPATsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/auth/tokens`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * List personal access tokens (PAT)
     */
    async listPATs(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.listPATsRaw(initOverrides);
    }

}
