/* tslint:disable */
/* eslint-disable */
/**
 * Intent API
 * REST API for the Intent Ecosystem (source of truth for clients and SDKs).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  Intent,
  IntentCreateRequest,
  IntentListResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    IntentFromJSON,
    IntentToJSON,
    IntentCreateRequestFromJSON,
    IntentCreateRequestToJSON,
    IntentListResponseFromJSON,
    IntentListResponseToJSON,
} from '../models/index';

export interface CreateIntentRequest {
    intentCreateRequest: IntentCreateRequest;
}

export interface GetIntentByIdRequest {
    intentId: string;
}

export interface ListIntentsRequest {
    limit?: number;
    cursor?: string;
}

/**
 * 
 */
export class IntentsApi extends runtime.BaseAPI {

    /**
     * Create a new intent
     */
    async createIntentRaw(requestParameters: CreateIntentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Intent>> {
        if (requestParameters['intentCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'intentCreateRequest',
                'Required parameter "intentCreateRequest" was null or undefined when calling createIntent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/intents`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IntentCreateRequestToJSON(requestParameters['intentCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IntentFromJSON(jsonValue));
    }

    /**
     * Create a new intent
     */
    async createIntent(requestParameters: CreateIntentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Intent> {
        const response = await this.createIntentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get intent by id
     */
    async getIntentByIdRaw(requestParameters: GetIntentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Intent>> {
        if (requestParameters['intentId'] == null) {
            throw new runtime.RequiredError(
                'intentId',
                'Required parameter "intentId" was null or undefined when calling getIntentById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/intents/{intentId}`.replace(`{${"intentId"}}`, encodeURIComponent(String(requestParameters['intentId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IntentFromJSON(jsonValue));
    }

    /**
     * Get intent by id
     */
    async getIntentById(requestParameters: GetIntentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Intent> {
        const response = await this.getIntentByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List intents
     */
    async listIntentsRaw(requestParameters: ListIntentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IntentListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/intents`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IntentListResponseFromJSON(jsonValue));
    }

    /**
     * List intents
     */
    async listIntents(requestParameters: ListIntentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IntentListResponse> {
        const response = await this.listIntentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
