/* tslint:disable */
/* eslint-disable */
/**
 * Intent API
 * REST API for the Intent Ecosystem.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PackagesListResponse,
} from '../models/index';
import {
    PackagesListResponseFromJSON,
    PackagesListResponseToJSON,
} from '../models/index';

export interface ListPackagesRequest {
    q?: string;
    limit?: number;
    offset?: number;
}

export interface ResolvePackageRequest {
    scope: string;
    name: string;
    version?: string;
    channel?: ResolvePackageChannelEnum;
}

/**
 * 
 */
export class PackagesApi extends runtime.BaseAPI {

    /**
     * Create package
     */
    async createPackageRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/packages`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create package
     */
    async createPackage(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createPackageRaw(initOverrides);
    }

    /**
     * List public packages for catalog discovery
     */
    async listPackagesRaw(requestParameters: ListPackagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PackagesListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/packages`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PackagesListResponseFromJSON(jsonValue));
    }

    /**
     * List public packages for catalog discovery
     */
    async listPackages(requestParameters: ListPackagesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PackagesListResponse> {
        const response = await this.listPackagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Resolve package install target
     */
    async resolvePackageRaw(requestParameters: ResolvePackageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['scope'] == null) {
            throw new runtime.RequiredError(
                'scope',
                'Required parameter "scope" was null or undefined when calling resolvePackage().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling resolvePackage().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['version'] != null) {
            queryParameters['version'] = requestParameters['version'];
        }

        if (requestParameters['channel'] != null) {
            queryParameters['channel'] = requestParameters['channel'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/packages/{scope}/{name}/resolve`.replace(`{${"scope"}}`, encodeURIComponent(String(requestParameters['scope']))).replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Resolve package install target
     */
    async resolvePackage(requestParameters: ResolvePackageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.resolvePackageRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const ResolvePackageChannelEnum = {
    Latest: 'latest',
    Stable: 'stable',
    Beta: 'beta',
    Nightly: 'nightly'
} as const;
export type ResolvePackageChannelEnum = typeof ResolvePackageChannelEnum[keyof typeof ResolvePackageChannelEnum];
