/* tslint:disable */
/* eslint-disable */
/**
 * Intent API
 * REST API for the Intent Ecosystem.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface V1PackagesScopeNameTagsGetRequest {
    scope: string;
    name: string;
}

export interface V1PackagesScopeNameTagsTagPutRequest {
    scope: string;
    name: string;
    tag: string;
}

export interface V1PackagesScopeNameVersionsVersionDeprecatePutRequest {
    scope: string;
    name: string;
    version: string;
}

export interface V1PackagesScopeNameVersionsVersionQuarantinePutRequest {
    scope: string;
    name: string;
    version: string;
}

export interface V1PackagesScopeNameVersionsVersionUnquarantinePutRequest {
    scope: string;
    name: string;
    version: string;
}

/**
 * 
 */
export class RegistryGovernanceApi extends runtime.BaseAPI {

    /**
     * List dist-tags for a package
     */
    async v1PackagesScopeNameTagsGetRaw(requestParameters: V1PackagesScopeNameTagsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['scope'] == null) {
            throw new runtime.RequiredError(
                'scope',
                'Required parameter "scope" was null or undefined when calling v1PackagesScopeNameTagsGet().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling v1PackagesScopeNameTagsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/packages/{scope}/{name}/tags`.replace(`{${"scope"}}`, encodeURIComponent(String(requestParameters['scope']))).replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * List dist-tags for a package
     */
    async v1PackagesScopeNameTagsGet(requestParameters: V1PackagesScopeNameTagsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1PackagesScopeNameTagsGetRaw(requestParameters, initOverrides);
    }

    /**
     * Set dist-tag target version (admin)
     */
    async v1PackagesScopeNameTagsTagPutRaw(requestParameters: V1PackagesScopeNameTagsTagPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['scope'] == null) {
            throw new runtime.RequiredError(
                'scope',
                'Required parameter "scope" was null or undefined when calling v1PackagesScopeNameTagsTagPut().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling v1PackagesScopeNameTagsTagPut().'
            );
        }

        if (requestParameters['tag'] == null) {
            throw new runtime.RequiredError(
                'tag',
                'Required parameter "tag" was null or undefined when calling v1PackagesScopeNameTagsTagPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/packages/{scope}/{name}/tags/{tag}`.replace(`{${"scope"}}`, encodeURIComponent(String(requestParameters['scope']))).replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))).replace(`{${"tag"}}`, encodeURIComponent(String(requestParameters['tag']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Set dist-tag target version (admin)
     */
    async v1PackagesScopeNameTagsTagPut(requestParameters: V1PackagesScopeNameTagsTagPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1PackagesScopeNameTagsTagPutRaw(requestParameters, initOverrides);
    }

    /**
     * Deprecate or clear deprecation for a version
     */
    async v1PackagesScopeNameVersionsVersionDeprecatePutRaw(requestParameters: V1PackagesScopeNameVersionsVersionDeprecatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['scope'] == null) {
            throw new runtime.RequiredError(
                'scope',
                'Required parameter "scope" was null or undefined when calling v1PackagesScopeNameVersionsVersionDeprecatePut().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling v1PackagesScopeNameVersionsVersionDeprecatePut().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling v1PackagesScopeNameVersionsVersionDeprecatePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/packages/{scope}/{name}/versions/{version}/deprecate`.replace(`{${"scope"}}`, encodeURIComponent(String(requestParameters['scope']))).replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))).replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deprecate or clear deprecation for a version
     */
    async v1PackagesScopeNameVersionsVersionDeprecatePut(requestParameters: V1PackagesScopeNameVersionsVersionDeprecatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1PackagesScopeNameVersionsVersionDeprecatePutRaw(requestParameters, initOverrides);
    }

    /**
     * Quarantine a version (admin)
     */
    async v1PackagesScopeNameVersionsVersionQuarantinePutRaw(requestParameters: V1PackagesScopeNameVersionsVersionQuarantinePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['scope'] == null) {
            throw new runtime.RequiredError(
                'scope',
                'Required parameter "scope" was null or undefined when calling v1PackagesScopeNameVersionsVersionQuarantinePut().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling v1PackagesScopeNameVersionsVersionQuarantinePut().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling v1PackagesScopeNameVersionsVersionQuarantinePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/packages/{scope}/{name}/versions/{version}/quarantine`.replace(`{${"scope"}}`, encodeURIComponent(String(requestParameters['scope']))).replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))).replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Quarantine a version (admin)
     */
    async v1PackagesScopeNameVersionsVersionQuarantinePut(requestParameters: V1PackagesScopeNameVersionsVersionQuarantinePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1PackagesScopeNameVersionsVersionQuarantinePutRaw(requestParameters, initOverrides);
    }

    /**
     * Remove quarantine from a version (admin)
     */
    async v1PackagesScopeNameVersionsVersionUnquarantinePutRaw(requestParameters: V1PackagesScopeNameVersionsVersionUnquarantinePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['scope'] == null) {
            throw new runtime.RequiredError(
                'scope',
                'Required parameter "scope" was null or undefined when calling v1PackagesScopeNameVersionsVersionUnquarantinePut().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling v1PackagesScopeNameVersionsVersionUnquarantinePut().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling v1PackagesScopeNameVersionsVersionUnquarantinePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/packages/{scope}/{name}/versions/{version}/unquarantine`.replace(`{${"scope"}}`, encodeURIComponent(String(requestParameters['scope']))).replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))).replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove quarantine from a version (admin)
     */
    async v1PackagesScopeNameVersionsVersionUnquarantinePut(requestParameters: V1PackagesScopeNameVersionsVersionUnquarantinePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1PackagesScopeNameVersionsVersionUnquarantinePutRaw(requestParameters, initOverrides);
    }

}
