/* tslint:disable */
/* eslint-disable */
/**
 * Intent API
 * REST API for the Intent Ecosystem.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface V1IndexChangesGetRequest {
    since?: number;
}

export interface V1IndexPkgScopeNameGetRequest {
    scope: string;
    name: string;
}

/**
 * 
 */
export class RegistryIndexApi extends runtime.BaseAPI {

    /**
     * Incremental index change feed
     */
    async v1IndexChangesGetRaw(requestParameters: V1IndexChangesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['since'] != null) {
            queryParameters['since'] = requestParameters['since'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/index/changes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Incremental index change feed
     */
    async v1IndexChangesGet(requestParameters: V1IndexChangesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1IndexChangesGetRaw(requestParameters, initOverrides);
    }

    /**
     * Compact package metadata for clients
     */
    async v1IndexPkgScopeNameGetRaw(requestParameters: V1IndexPkgScopeNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['scope'] == null) {
            throw new runtime.RequiredError(
                'scope',
                'Required parameter "scope" was null or undefined when calling v1IndexPkgScopeNameGet().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling v1IndexPkgScopeNameGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/index/pkg/{scope}/{name}`.replace(`{${"scope"}}`, encodeURIComponent(String(requestParameters['scope']))).replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Compact package metadata for clients
     */
    async v1IndexPkgScopeNameGet(requestParameters: V1IndexPkgScopeNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1IndexPkgScopeNameGetRaw(requestParameters, initOverrides);
    }

}
