/* tslint:disable */
/* eslint-disable */
/**
 * Intent API
 * REST API for the Intent Ecosystem.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface V1PackagesScopeNameVersionsVersionProvenanceGetRequest {
    scope: string;
    name: string;
    version: string;
}

export interface V1PackagesScopeNameVersionsVersionProvenancePutRequest {
    scope: string;
    name: string;
    version: string;
}

/**
 * 
 */
export class TrustedPublishingApi extends runtime.BaseAPI {

    /**
     * Get provenance for a package version
     */
    async v1PackagesScopeNameVersionsVersionProvenanceGetRaw(requestParameters: V1PackagesScopeNameVersionsVersionProvenanceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['scope'] == null) {
            throw new runtime.RequiredError(
                'scope',
                'Required parameter "scope" was null or undefined when calling v1PackagesScopeNameVersionsVersionProvenanceGet().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling v1PackagesScopeNameVersionsVersionProvenanceGet().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling v1PackagesScopeNameVersionsVersionProvenanceGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/packages/{scope}/{name}/versions/{version}/provenance`.replace(`{${"scope"}}`, encodeURIComponent(String(requestParameters['scope']))).replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))).replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get provenance for a package version
     */
    async v1PackagesScopeNameVersionsVersionProvenanceGet(requestParameters: V1PackagesScopeNameVersionsVersionProvenanceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1PackagesScopeNameVersionsVersionProvenanceGetRaw(requestParameters, initOverrides);
    }

    /**
     * Upsert provenance for a package version
     */
    async v1PackagesScopeNameVersionsVersionProvenancePutRaw(requestParameters: V1PackagesScopeNameVersionsVersionProvenancePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['scope'] == null) {
            throw new runtime.RequiredError(
                'scope',
                'Required parameter "scope" was null or undefined when calling v1PackagesScopeNameVersionsVersionProvenancePut().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling v1PackagesScopeNameVersionsVersionProvenancePut().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling v1PackagesScopeNameVersionsVersionProvenancePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/packages/{scope}/{name}/versions/{version}/provenance`.replace(`{${"scope"}}`, encodeURIComponent(String(requestParameters['scope']))).replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))).replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Upsert provenance for a package version
     */
    async v1PackagesScopeNameVersionsVersionProvenancePut(requestParameters: V1PackagesScopeNameVersionsVersionProvenancePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1PackagesScopeNameVersionsVersionProvenancePutRaw(requestParameters, initOverrides);
    }

    /**
     * Exchange trusted OIDC identity for short-lived publish token
     */
    async v1PublishOidcExchangePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/publish/oidc/exchange`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Exchange trusted OIDC identity for short-lived publish token
     */
    async v1PublishOidcExchangePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1PublishOidcExchangePostRaw(initOverrides);
    }

}
