/* tslint:disable */
/* eslint-disable */
/**
 * Intent API
 * REST API for the Intent Ecosystem.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthPasswordResetRequest200Response
 */
export interface AuthPasswordResetRequest200Response {
    /**
     * 
     * @type {string}
     * @memberof AuthPasswordResetRequest200Response
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthPasswordResetRequest200Response
     */
    resetToken?: string;
    /**
     * 
     * @type {number}
     * @memberof AuthPasswordResetRequest200Response
     */
    expiresIn?: number;
}

/**
 * Check if a given object implements the AuthPasswordResetRequest200Response interface.
 */
export function instanceOfAuthPasswordResetRequest200Response(value: object): value is AuthPasswordResetRequest200Response {
    return true;
}

export function AuthPasswordResetRequest200ResponseFromJSON(json: any): AuthPasswordResetRequest200Response {
    return AuthPasswordResetRequest200ResponseFromJSONTyped(json, false);
}

export function AuthPasswordResetRequest200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthPasswordResetRequest200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'resetToken': json['resetToken'] == null ? undefined : json['resetToken'],
        'expiresIn': json['expiresIn'] == null ? undefined : json['expiresIn'],
    };
}

export function AuthPasswordResetRequest200ResponseToJSON(value?: AuthPasswordResetRequest200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'resetToken': value['resetToken'],
        'expiresIn': value['expiresIn'],
    };
}

