/* tslint:disable */
/* eslint-disable */
/**
 * Intent API
 * REST API for the Intent Ecosystem.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthPasswordResetRequestRequest
 */
export interface AuthPasswordResetRequestRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthPasswordResetRequestRequest
     */
    email: string;
}

/**
 * Check if a given object implements the AuthPasswordResetRequestRequest interface.
 */
export function instanceOfAuthPasswordResetRequestRequest(value: object): value is AuthPasswordResetRequestRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function AuthPasswordResetRequestRequestFromJSON(json: any): AuthPasswordResetRequestRequest {
    return AuthPasswordResetRequestRequestFromJSONTyped(json, false);
}

export function AuthPasswordResetRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthPasswordResetRequestRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function AuthPasswordResetRequestRequestToJSON(value?: AuthPasswordResetRequestRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
    };
}

