/* tslint:disable */
/* eslint-disable */
/**
 * Intent API
 * REST API for the Intent Ecosystem.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthPasswordResetConfirmRequest
 */
export interface AuthPasswordResetConfirmRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthPasswordResetConfirmRequest
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof AuthPasswordResetConfirmRequest
     */
    newPassword: string;
}

/**
 * Check if a given object implements the AuthPasswordResetConfirmRequest interface.
 */
export function instanceOfAuthPasswordResetConfirmRequest(value: object): value is AuthPasswordResetConfirmRequest {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function AuthPasswordResetConfirmRequestFromJSON(json: any): AuthPasswordResetConfirmRequest {
    return AuthPasswordResetConfirmRequestFromJSONTyped(json, false);
}

export function AuthPasswordResetConfirmRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthPasswordResetConfirmRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'newPassword': json['newPassword'],
    };
}

export function AuthPasswordResetConfirmRequestToJSON(value?: AuthPasswordResetConfirmRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'token': value['token'],
        'newPassword': value['newPassword'],
    };
}

