/* tslint:disable */
/* eslint-disable */
/**
 * Intent API
 * REST API for the Intent Ecosystem.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLogoutRequest
 */
export interface AuthLogoutRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthLogoutRequest
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the AuthLogoutRequest interface.
 */
export function instanceOfAuthLogoutRequest(value: object): value is AuthLogoutRequest {
    return true;
}

export function AuthLogoutRequestFromJSON(json: any): AuthLogoutRequest {
    return AuthLogoutRequestFromJSONTyped(json, false);
}

export function AuthLogoutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLogoutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function AuthLogoutRequestToJSON(value?: AuthLogoutRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'refreshToken': value['refreshToken'],
    };
}

