/* tslint:disable */
/* eslint-disable */
/**
 * Intent API
 * REST API for the Intent Ecosystem (source of truth for clients and SDKs).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthTokens
 */
export interface AuthTokens {
    /**
     * 
     * @type {string}
     * @memberof AuthTokens
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof AuthTokens
     */
    refreshToken: string;
    /**
     * Seconds until expiration
     * @type {number}
     * @memberof AuthTokens
     */
    expiresIn: number;
}

/**
 * Check if a given object implements the AuthTokens interface.
 */
export function instanceOfAuthTokens(value: object): value is AuthTokens {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    return true;
}

export function AuthTokensFromJSON(json: any): AuthTokens {
    return AuthTokensFromJSONTyped(json, false);
}

export function AuthTokensFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthTokens {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
        'refreshToken': json['refreshToken'],
        'expiresIn': json['expiresIn'],
    };
}

export function AuthTokensToJSON(value?: AuthTokens | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
        'expiresIn': value['expiresIn'],
    };
}

