/* tslint:disable */
/* eslint-disable */
/**
 * Intent API
 * REST API for the Intent Ecosystem.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface AuthSessionResponse
 */
export interface AuthSessionResponse {
    /**
     * 
     * @type {User}
     * @memberof AuthSessionResponse
     */
    user: User;
    /**
     * 
     * @type {string}
     * @memberof AuthSessionResponse
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof AuthSessionResponse
     */
    refreshToken: string;
    /**
     * 
     * @type {number}
     * @memberof AuthSessionResponse
     */
    expiresIn: number;
}

/**
 * Check if a given object implements the AuthSessionResponse interface.
 */
export function instanceOfAuthSessionResponse(value: object): value is AuthSessionResponse {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    return true;
}

export function AuthSessionResponseFromJSON(json: any): AuthSessionResponse {
    return AuthSessionResponseFromJSONTyped(json, false);
}

export function AuthSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserFromJSON(json['user']),
        'accessToken': json['accessToken'],
        'refreshToken': json['refreshToken'],
        'expiresIn': json['expiresIn'],
    };
}

export function AuthSessionResponseToJSON(value?: AuthSessionResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user': UserToJSON(value['user']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
        'expiresIn': value['expiresIn'],
    };
}

