/* tslint:disable */
/* eslint-disable */
/**
 * Intent API
 * REST API for the Intent Ecosystem (source of truth for clients and SDKs).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IntentCreateRequest
 */
export interface IntentCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof IntentCreateRequest
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof IntentCreateRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof IntentCreateRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the IntentCreateRequest interface.
 */
export function instanceOfIntentCreateRequest(value: object): value is IntentCreateRequest {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function IntentCreateRequestFromJSON(json: any): IntentCreateRequest {
    return IntentCreateRequestFromJSONTyped(json, false);
}

export function IntentCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntentCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function IntentCreateRequestToJSON(value?: IntentCreateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'key': value['key'],
        'title': value['title'],
        'description': value['description'],
    };
}

