/* tslint:disable */
/* eslint-disable */
/**
 * Intent API
 * REST API for the Intent Ecosystem (source of truth for clients and SDKs).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Intent } from './Intent';
import {
    IntentFromJSON,
    IntentFromJSONTyped,
    IntentToJSON,
} from './Intent';

/**
 * 
 * @export
 * @interface IntentListResponse
 */
export interface IntentListResponse {
    /**
     * 
     * @type {Array<Intent>}
     * @memberof IntentListResponse
     */
    items: Array<Intent>;
    /**
     * 
     * @type {string}
     * @memberof IntentListResponse
     */
    nextCursor?: string;
}

/**
 * Check if a given object implements the IntentListResponse interface.
 */
export function instanceOfIntentListResponse(value: object): value is IntentListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function IntentListResponseFromJSON(json: any): IntentListResponse {
    return IntentListResponseFromJSONTyped(json, false);
}

export function IntentListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntentListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(IntentFromJSON)),
        'nextCursor': json['nextCursor'] == null ? undefined : json['nextCursor'],
    };
}

export function IntentListResponseToJSON(value?: IntentListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(IntentToJSON)),
        'nextCursor': value['nextCursor'],
    };
}

