/* tslint:disable */
/* eslint-disable */
/**
 * Intent API
 * REST API for the Intent Ecosystem (source of truth for clients and SDKs).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Intent
 */
export interface Intent {
    /**
     * 
     * @type {string}
     * @memberof Intent
     */
    id: string;
    /**
     * Unique intent key (slug-like)
     * @type {string}
     * @memberof Intent
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof Intent
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Intent
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Intent
     */
    version?: string;
    /**
     * 
     * @type {Date}
     * @memberof Intent
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the Intent interface.
 */
export function instanceOfIntent(value: object): value is Intent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function IntentFromJSON(json: any): Intent {
    return IntentFromJSONTyped(json, false);
}

export function IntentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Intent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'key': json['key'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'version': json['version'] == null ? undefined : json['version'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function IntentToJSON(value?: Intent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'key': value['key'],
        'title': value['title'],
        'description': value['description'],
        'version': value['version'],
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

