/* tslint:disable */
/* eslint-disable */
/**
 * Intent API
 * REST API for the Intent Ecosystem.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PackageListItem
 */
export interface PackageListItem {
    /**
     * 
     * @type {number}
     * @memberof PackageListItem
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PackageListItem
     */
    scope: string;
    /**
     * 
     * @type {string}
     * @memberof PackageListItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PackageListItem
     */
    visibility?: string;
    /**
     * 
     * @type {string}
     * @memberof PackageListItem
     */
    description?: string;
}

/**
 * Check if a given object implements the PackageListItem interface.
 */
export function instanceOfPackageListItem(value: object): value is PackageListItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PackageListItemFromJSON(json: any): PackageListItem {
    return PackageListItemFromJSONTyped(json, false);
}

export function PackageListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackageListItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'scope': json['scope'],
        'name': json['name'],
        'visibility': json['visibility'] == null ? undefined : json['visibility'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function PackageListItemToJSON(value?: PackageListItem | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'scope': value['scope'],
        'name': value['name'],
        'visibility': value['visibility'],
        'description': value['description'],
    };
}

