/* tslint:disable */
/* eslint-disable */
/**
 * Intent API
 * REST API for the Intent Ecosystem.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PackageListItem } from './PackageListItem';
import {
    PackageListItemFromJSON,
    PackageListItemFromJSONTyped,
    PackageListItemToJSON,
} from './PackageListItem';
import type { PackagesPagination } from './PackagesPagination';
import {
    PackagesPaginationFromJSON,
    PackagesPaginationFromJSONTyped,
    PackagesPaginationToJSON,
} from './PackagesPagination';

/**
 * 
 * @export
 * @interface PackagesListResponse
 */
export interface PackagesListResponse {
    /**
     * 
     * @type {Array<PackageListItem>}
     * @memberof PackagesListResponse
     */
    items: Array<PackageListItem>;
    /**
     * 
     * @type {PackagesPagination}
     * @memberof PackagesListResponse
     */
    pagination: PackagesPagination;
}

/**
 * Check if a given object implements the PackagesListResponse interface.
 */
export function instanceOfPackagesListResponse(value: object): value is PackagesListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function PackagesListResponseFromJSON(json: any): PackagesListResponse {
    return PackagesListResponseFromJSONTyped(json, false);
}

export function PackagesListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackagesListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PackageListItemFromJSON)),
        'pagination': PackagesPaginationFromJSON(json['pagination']),
    };
}

export function PackagesListResponseToJSON(value?: PackagesListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(PackageListItemToJSON)),
        'pagination': PackagesPaginationToJSON(value['pagination']),
    };
}

