/* tslint:disable */
/* eslint-disable */
/**
 * Intent API
 * REST API for the Intent Ecosystem.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PackagesPagination
 */
export interface PackagesPagination {
    /**
     * 
     * @type {number}
     * @memberof PackagesPagination
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof PackagesPagination
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof PackagesPagination
     */
    offset: number;
}

/**
 * Check if a given object implements the PackagesPagination interface.
 */
export function instanceOfPackagesPagination(value: object): value is PackagesPagination {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function PackagesPaginationFromJSON(json: any): PackagesPagination {
    return PackagesPaginationFromJSONTyped(json, false);
}

export function PackagesPaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackagesPagination {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'limit': json['limit'],
        'offset': json['offset'],
    };
}

export function PackagesPaginationToJSON(value?: PackagesPagination | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'total': value['total'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

