/* tslint:disable */
/* eslint-disable */
/**
 * Intent API
 * REST API for the Intent Ecosystem.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Scope
 */
export interface Scope {
    /**
     * 
     * @type {number}
     * @memberof Scope
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Scope
     */
    orgId?: number;
    /**
     * 
     * @type {string}
     * @memberof Scope
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Scope
     */
    type: ScopeTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Scope
     */
    verificationStatus: ScopeVerificationStatusEnum;
}


/**
 * @export
 */
export const ScopeTypeEnum = {
    User: 'user',
    Org: 'org'
} as const;
export type ScopeTypeEnum = typeof ScopeTypeEnum[keyof typeof ScopeTypeEnum];

/**
 * @export
 */
export const ScopeVerificationStatusEnum = {
    Unverified: 'unverified',
    Pending: 'pending',
    Verified: 'verified',
    Revoked: 'revoked'
} as const;
export type ScopeVerificationStatusEnum = typeof ScopeVerificationStatusEnum[keyof typeof ScopeVerificationStatusEnum];


/**
 * Check if a given object implements the Scope interface.
 */
export function instanceOfScope(value: object): value is Scope {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('verificationStatus' in value) || value['verificationStatus'] === undefined) return false;
    return true;
}

export function ScopeFromJSON(json: any): Scope {
    return ScopeFromJSONTyped(json, false);
}

export function ScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Scope {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'orgId': json['org_id'] == null ? undefined : json['org_id'],
        'name': json['name'],
        'type': json['type'],
        'verificationStatus': json['verification_status'],
    };
}

export function ScopeToJSON(value?: Scope | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'org_id': value['orgId'],
        'name': value['name'],
        'type': value['type'],
        'verification_status': value['verificationStatus'],
    };
}

