/* tslint:disable */
/* eslint-disable */
/**
 * Intent API
 * REST API for the Intent Ecosystem.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserProfileRequest
 */
export interface UpdateUserProfileRequest {
    /**
     * Display name. Use an empty string to clear.
     * @type {string}
     * @memberof UpdateUserProfileRequest
     */
    name: string;
}

/**
 * Check if a given object implements the UpdateUserProfileRequest interface.
 */
export function instanceOfUpdateUserProfileRequest(value: object): value is UpdateUserProfileRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateUserProfileRequestFromJSON(json: any): UpdateUserProfileRequest {
    return UpdateUserProfileRequestFromJSONTyped(json, false);
}

export function UpdateUserProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserProfileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function UpdateUserProfileRequestToJSON(value?: UpdateUserProfileRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

